name: Build Chopin Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Cấp quyền tạo Release

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Build Environment
        run: |
          sudo apt update
          sudo apt install -y build-essential bc bison flex libssl-dev libelf-dev zip ccache

      - name: Run Build Script
        run: |
          chmod +x build.sh
          ./build.sh chopin 2>&1 | tee build.log

      - name: Upload Build Log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Build-Log-Chopin
          path: build.log

      - name: Create GitHub Release
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          tag_name: kernel-build-${{ github.run_number }}
          name: Chopin Kernel Build #${{ github.run_number }}
          files: "**/*.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
