name: Build Chopin Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Build Environment
        run: |
          sudo apt update
          sudo apt install -y build-essential bc bison flex libssl-dev libelf-dev zip ccache

      - name: Run Build Script
        run: |
          chmod +x build.sh
          # Ghi toàn bộ output ra file build.log và vẫn in ra màn hình console
          ./build.sh chopin 2>&1 | tee build.log

      - name: Upload Build Log
        if: always() # Luôn lưu log kể cả khi build thất bại để soi lỗi
        uses: actions/upload-artifact@v4
        with:
          name: Build-Log-Chopin
          path: build.log

      - name: Upload Flashable Zip
        if: success() # Chỉ upload zip khi build thành công
        uses: actions/upload-artifact@v4
        with:
          name: HydrogenKernel-Chopin-Spoofed
          path: "*.zip"
